name: Recovery Build      

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: windows-latest
    uses: Windows3280/XiaoMiToolV2-bld
    steps:

    - name: Gradlew building
      run: |
      "gradlew.bat build && gradlew.bat run"
      "dir"
      "dir -w"
      "dir -s"
      id: pwd

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          rel (a)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
